package com.atoussec.transfers.domain.exception;

public enum DomainError {
  INVALID_MONEY,
  INVALID_IDENTIFIER,
  SAME_ACCOUNT_TRANSFER,
  INACTIVE_USER,
  MERCHANT_CANNOT_TRANSFER,
  PARTICIPANT_MISMATCH,
  INVALID_WALLET_BALANCE,
  INSUFFICIENT_FUNDS,
  WALLET_OWNERSHIP_MISMATCH
}
