CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(120) NOT NULL,
    tax_id_normalized VARCHAR(14) NOT NULL,
    email_normalized VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_tax_id_normalized UNIQUE (tax_id_normalized),
    CONSTRAINT uk_users_email_normalized UNIQUE (email_normalized),
    CONSTRAINT ck_users_full_name CHECK (btrim(full_name) <> ''),
    CONSTRAINT ck_users_tax_id_normalized
        CHECK (tax_id_normalized ~ '^(\d{11}|\d{14})$'),
    CONSTRAINT ck_users_email_normalized
        CHECK (
            email_normalized = lower(btrim(email_normalized))
            AND position('@' IN email_normalized) > 1
        ),
    CONSTRAINT ck_users_password_hash CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_users_type CHECK (type IN ('CUSTOMER', 'MERCHANT')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_wallets PRIMARY KEY (id),
    CONSTRAINT fk_wallets_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uk_wallets_user_id UNIQUE (user_id),
    CONSTRAINT ck_wallets_balance_non_negative
        CHECK (balance >= 0 AND balance <> 'NaN'::NUMERIC),
    CONSTRAINT ck_wallets_version_non_negative CHECK (version >= 0)
);

CREATE TABLE transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id CHAR(26) NOT NULL,
    payer_id BIGINT NOT NULL,
    payee_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'BRL',
    status VARCHAR(16) NOT NULL DEFAULT 'COMPLETED',
    idempotency_key VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_transfers PRIMARY KEY (id),
    CONSTRAINT fk_transfers_payer_id
        FOREIGN KEY (payer_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transfers_payee_id
        FOREIGN KEY (payee_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uk_transfers_public_id UNIQUE (public_id),
    CONSTRAINT uk_transfers_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_transfers_public_id
        CHECK (public_id ~ '^[0-7][0-9A-HJKMNP-TV-Z]{25}$'),
    CONSTRAINT ck_transfers_participants CHECK (payer_id <> payee_id),
    CONSTRAINT ck_transfers_amount_positive
        CHECK (amount > 0 AND amount <> 'NaN'::NUMERIC),
    CONSTRAINT ck_transfers_currency CHECK (currency = 'BRL'),
    CONSTRAINT ck_transfers_status CHECK (status = 'COMPLETED')
);

CREATE INDEX ix_transfers_payer_created_at
    ON transfers (payer_id, created_at DESC);

CREATE INDEX ix_transfers_payee_created_at
    ON transfers (payee_id, created_at DESC);

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transfer_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    entry_type VARCHAR(8) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ledger_entries PRIMARY KEY (id),
    CONSTRAINT fk_ledger_entries_transfer_id
        FOREIGN KEY (transfer_id) REFERENCES transfers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ledger_entries_wallet_id
        FOREIGN KEY (wallet_id) REFERENCES wallets (id) ON DELETE RESTRICT,
    CONSTRAINT uk_ledger_entries_transfer_type UNIQUE (transfer_id, entry_type),
    CONSTRAINT ck_ledger_entries_type CHECK (entry_type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_ledger_entries_amount_positive
        CHECK (amount > 0 AND amount <> 'NaN'::NUMERIC)
);

CREATE INDEX ix_ledger_entries_wallet_created_at
    ON ledger_entries (wallet_id, created_at DESC);

CREATE FUNCTION is_transfer_ledger_balanced(target_transfer_id BIGINT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
AS $$
    SELECT
        count(ledger.id) = 2
        AND count(ledger.id) FILTER (WHERE ledger.entry_type = 'DEBIT') = 1
        AND count(ledger.id) FILTER (WHERE ledger.entry_type = 'CREDIT') = 1
        AND count(ledger.id) FILTER (
            WHERE ledger.entry_type = 'DEBIT' AND wallet.user_id = transfer.payer_id
        ) = 1
        AND count(ledger.id) FILTER (
            WHERE ledger.entry_type = 'CREDIT' AND wallet.user_id = transfer.payee_id
        ) = 1
        AND bool_and(ledger.amount = transfer.amount)
    FROM transfers AS transfer
    LEFT JOIN ledger_entries AS ledger ON ledger.transfer_id = transfer.id
    LEFT JOIN wallets AS wallet ON wallet.id = ledger.wallet_id
    WHERE transfer.id = target_transfer_id
    GROUP BY transfer.id
$$;

CREATE FUNCTION enforce_transfer_ledger_balance()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT COALESCE(is_transfer_ledger_balanced(NEW.id), FALSE) THEN
        RAISE EXCEPTION 'ck_ledger_entries_balanced violated for transfer %', NEW.id
            USING ERRCODE = '23514', CONSTRAINT = 'ck_ledger_entries_balanced';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION enforce_ledger_entry_balance()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT COALESCE(is_transfer_ledger_balanced(NEW.transfer_id), FALSE) THEN
        RAISE EXCEPTION 'ck_ledger_entries_balanced violated for transfer %', NEW.transfer_id
            USING ERRCODE = '23514', CONSTRAINT = 'ck_ledger_entries_balanced';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION prevent_ledger_entry_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'ck_ledger_entries_immutable forbids update or delete'
        USING ERRCODE = '23514', CONSTRAINT = 'ck_ledger_entries_immutable';
END;
$$;

CREATE CONSTRAINT TRIGGER ck_transfers_balanced_ledger
AFTER INSERT ON transfers
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_transfer_ledger_balance();

CREATE CONSTRAINT TRIGGER ck_ledger_entries_balanced
AFTER INSERT ON ledger_entries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION enforce_ledger_entry_balance();

CREATE TRIGGER ck_ledger_entries_immutable
BEFORE UPDATE OR DELETE ON ledger_entries
FOR EACH ROW
EXECUTE FUNCTION prevent_ledger_entry_mutation();
